import type { Car } from "~/types";

export const cars: Car[] = [
  {
    id: "1",
    name: "Toyota Fortuner",
    brand: "Toyota",
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Diesel",
    registrationNo: "GJ01AB1234",
    seats: 7,
    basePricePerHour: 350,
    depositAmount: 5000,
    status: "available",
    city: "Ahmedabad",
    coverImage: "https://cdn.velorent.com/cars/fortuner/cover.jpg",
    galleryImages: [
      "https://cdn.velorent.com/cars/fortuner/front.jpg",
      "https://cdn.velorent.com/cars/fortuner/interior.jpg",
      "https://cdn.velorent.com/cars/fortuner/rear.jpg",
    ],
  },
  {
    id: "2",
    name: "Honda City ZX",
    brand: "Honda",
    type: "Sedan",
    transmission: "Manual",
    fuelType: "Petrol",
    registrationNo: "GJ05CD5678",
    seats: 5,
    basePricePerHour: 220,
    depositAmount: 4000,
    status: "rented",
    city: "Vadodara",
    coverImage: "https://cdn.velorent.com/cars/honda-city/cover.jpg",
    galleryImages: [
      "https://cdn.velorent.com/cars/honda-city/front.jpg",
      "https://cdn.velorent.com/cars/honda-city/interior.jpg",
      "https://cdn.velorent.com/cars/honda-city/rear.jpg",
    ],
  },
  {
    id: "3",
    name: "Tata Nexon EV",
    brand: "Tata",
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Electric",
    registrationNo: "GJ27EF9876",
    seats: 5,
    basePricePerHour: 280,
    depositAmount: 4500,
    status: "booked",
    city: "Surat",
    coverImage: "https://cdn.velorent.com/cars/nexon-ev/cover.jpg",
    galleryImages: [
      "https://cdn.velorent.com/cars/nexon-ev/front.jpg",
      "https://cdn.velorent.com/cars/nexon-ev/interior.jpg",
      "https://cdn.velorent.com/cars/nexon-ev/rear.jpg",
    ],
  },
  {
    id: "4",
    name: "BMW 3 Series",
    brand: "BMW",
    type: "Sedan",
    transmission: "Automatic",
    fuelType: "Petrol",
    registrationNo: "GJ18GH4321",
    seats: 5,
    basePricePerHour: 720,
    depositAmount: 10000,
    status: "maintenance",
    city: "Ahmedabad",
    coverImage: "https://cdn.velorent.com/cars/bmw-3series/cover.jpg",
    galleryImages: [
      "https://cdn.velorent.com/cars/bmw-3series/front.jpg",
      "https://cdn.velorent.com/cars/bmw-3series/interior.jpg",
      "https://cdn.velorent.com/cars/bmw-3series/rear.jpg",
    ],
  },
  {
    id: "5",
    name: "Kia Sonet",
    brand: "Kia",
    type: "Crossover",
    transmission: "Manual",
    fuelType: "Diesel",
    registrationNo: "GJ09JK6543",
    seats: 5,
    basePricePerHour: 260,
    depositAmount: 4000,
    status: "available",
    city: "Rajkot",
    coverImage: "https://cdn.velorent.com/cars/kia-sonet/cover.jpg",
    galleryImages: [
      "https://cdn.velorent.com/cars/kia-sonet/front.jpg",
      "https://cdn.velorent.com/cars/kia-sonet/interior.jpg",
      "https://cdn.velorent.com/cars/kia-sonet/rear.jpg",
    ],
  },
];
