create table if not exists public.booking_location_updates (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy double precision check (accuracy is null or accuracy >= 0),
  recorded_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists booking_location_updates_booking_time_idx
  on public.booking_location_updates (booking_id, recorded_at);

alter table public.booking_location_updates enable row level security;

create policy "customers insert location for ongoing booking"
on public.booking_location_updates for insert to authenticated
with check (
  customer_id = auth.uid()
  and exists (
    select 1 from public.bookings b
    where b.id = booking_id
      and b.customer_id = auth.uid()
      and b.status = 'ongoing'
  )
);

create policy "customers read own booking locations"
on public.booking_location_updates for select to authenticated
using (customer_id = auth.uid());

create policy "admins read booking locations"
on public.booking_location_updates for select to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role_id = 1
  )
);

create or replace function public.find_booking_by_code(p_booking_code text)
returns table (id uuid, customer_id uuid, booking_code text)
language sql
security definer
set search_path = public
as $$
  select b.id, b.customer_id, upper(right(b.id::text, 8)) as booking_code
  from public.bookings b
  where upper(right(b.id::text, 8)) = upper(trim(leading '#' from trim(p_booking_code)))
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role_id = 1
    )
  limit 1;
$$;

revoke all on function public.find_booking_by_code(text) from public;
grant execute on function public.find_booking_by_code(text) to authenticated;
